"use client";

import { useState, useCallback, useEffect } from "react";
import type { Week, CalendarEvent, DayOfWeek, EventCategory } from "@/types";
import { getCurrentWeekStart } from "@/lib/dates";

const STORAGE_PREFIX = "weekplanner_week_";

/** Input data for creating a new event — ID and timestamps are generated by the hook. */
export interface NewEventData {
  title: string;
  dayKey: DayOfWeek;
  startTime?: string;
  endTime?: string;
  category: EventCategory;
  note?: string;
}

function loadWeek(weekStart: string): Week {
  try {
    const raw = localStorage.getItem(STORAGE_PREFIX + weekStart);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed && Array.isArray(parsed.events)) {
        return { weekStart, events: parsed.events };
      }
    }
  } catch {
    // Corrupted data or localStorage unavailable — start fresh
  }
  return { weekStart, events: [] };
}

const VALID_DAYS: Set<string> = new Set(["mon", "tue", "wed", "thu", "fri", "sat", "sun"]);

/** Guards at the data boundary — rejects obviously invalid event data. */
function validateEventData(data: { title?: string; dayKey?: DayOfWeek; startTime?: string; endTime?: string }): void {
  if ("title" in data && !data.title?.trim()) {
    throw new Error("Event title is required");
  }
  if ("dayKey" in data && !VALID_DAYS.has(data.dayKey!)) {
    throw new Error("Event day must be within the current week");
  }
  if (data.startTime && data.endTime && data.endTime <= data.startTime) {
    throw new Error("End time must be after start time");
  }
}

function saveWeek(week: Week): void {
  try {
    localStorage.setItem(STORAGE_PREFIX + week.weekStart, JSON.stringify(week));
  } catch {
    // localStorage full or unavailable — silent fail, data stays in memory
  }
}

/**
 * Manages the current week's events with localStorage persistence.
 * Always scoped to the current week — no way to access other weeks.
 */
export function useWeekStorage() {
  const weekStart = getCurrentWeekStart();
  const [week, setWeek] = useState<Week>(() => loadWeek(weekStart));

  // Sync to localStorage on every change
  useEffect(() => {
    saveWeek(week);
  }, [week]);

  const addEvent = useCallback((data: NewEventData) => {
    validateEventData(data);

    const event: CalendarEvent = {
      id: crypto.randomUUID(),
      title: data.title.trim(),
      dayKey: data.dayKey,
      startTime: data.startTime || undefined,
      endTime: data.endTime || undefined,
      category: data.category,
      note: data.note?.trim() || undefined,
      status: "planned",
      createdAt: new Date().toISOString(),
    };

    setWeek((prev) => ({
      ...prev,
      events: [...prev.events, event],
    }));

    return event;
  }, []);

  const updateEvent = useCallback((id: string, updates: Partial<Omit<CalendarEvent, "id" | "createdAt">>) => {
    validateEventData(updates);

    setWeek((prev) => ({
      ...prev,
      events: prev.events.map((e) => (e.id === id ? { ...e, ...updates } : e)),
    }));
  }, []);

  const deleteEvent = useCallback((id: string) => {
    setWeek((prev) => ({
      ...prev,
      events: prev.events.filter((e) => e.id !== id),
    }));
  }, []);

  return { week, addEvent, updateEvent, deleteEvent };
}
