"use client";

import { useState, useCallback, useEffect } from "react";
import type { Week, CalendarEvent, DayOfWeek, EventCategory, EventVisibility } from "@/types";
import { getCurrentWeekStart } from "@/lib/dates";
import { createClient } from "@/lib/supabase";
import { useAuth } from "./useAuth";

/** Input data for creating a new event — ID and timestamps are generated by the hook. */
export interface NewEventData {
  title: string;
  dayKey: DayOfWeek;
  startTime?: string;
  endTime?: string;
  category: EventCategory;
  note?: string;
  visibility?: EventVisibility;
}

const VALID_DAYS: Set<string> = new Set(["mon", "tue", "wed", "thu", "fri", "sat", "sun"]);
const VALID_CATEGORIES: Set<string> = new Set(["work", "personal", "health", "errand", "other"]);
const VALID_STATUSES: Set<string> = new Set(["planned", "completed", "skipped"]);

/** Filters out corrupted events when loading. */
export function isValidEvent(e: unknown): e is CalendarEvent {
  if (!e || typeof e !== "object") return false;
  const ev = e as Record<string, unknown>;
  return (
    typeof ev.id === "string" &&
    typeof ev.title === "string" &&
    ev.title.trim().length > 0 &&
    typeof ev.dayKey === "string" &&
    VALID_DAYS.has(ev.dayKey) &&
    VALID_CATEGORIES.has(ev.category as string) &&
    VALID_STATUSES.has(ev.status as string)
  );
}

/** Guards at the data boundary — rejects obviously invalid event data. */
function validateEventData(data: { title?: string; dayKey?: DayOfWeek; startTime?: string; endTime?: string }): void {
  if ("title" in data && !data.title?.trim()) {
    throw new Error("Event title is required");
  }
  if ("dayKey" in data && !VALID_DAYS.has(data.dayKey!)) {
    throw new Error("Event day must be within the current week");
  }
  if (data.startTime && data.endTime && data.endTime <= data.startTime) {
    throw new Error("End time must be after start time");
  }
}

/** Maps a Supabase row to our CalendarEvent type. */
function rowToEvent(row: Record<string, unknown>): CalendarEvent {
  return {
    id: row.id as string,
    title: row.title as string,
    dayKey: row.day_key as DayOfWeek,
    startTime: (row.start_time as string) || undefined,
    endTime: (row.end_time as string) || undefined,
    category: row.category as EventCategory,
    status: row.status as CalendarEvent["status"],
    visibility: (row.visibility as EventVisibility) || "private",
    note: (row.note as string) || undefined,
    createdAt: row.created_at as string,
  };
}

/**
 * Manages the current week's events with Supabase persistence.
 * Always scoped to the authenticated user and current week.
 */
export function useWeekStorage() {
  const weekStart = getCurrentWeekStart();
  const { user } = useAuth();
  const [week, setWeek] = useState<Week>({ weekStart, events: [] });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Load events from Supabase on mount / when user changes
  useEffect(() => {
    if (!user) {
      setWeek({ weekStart, events: [] });
      setLoading(false);
      return;
    }

    let cancelled = false;
    async function load() {
      setError(null);
      try {
        const supabase = createClient();

        // Load user's own events
        const { data, error: queryError } = await supabase
          .from("events")
          .select("*")
          .eq("user_id", user!.id)
          .eq("week_start", weekStart)
          .order("created_at", { ascending: true });

        if (cancelled) return;

        if (queryError) {
          setError(queryError.message);
          if (!cancelled) setLoading(false);
          return;
        }

        const ownEvents = (data || []).map(rowToEvent).filter(isValidEvent);

        // Load accepted invited events (events from others where user is an accepted participant)
        const { data: participantRows } = await supabase
          .from("event_participants")
          .select("event_id")
          .eq("user_id", user!.id)
          .eq("status", "accepted");

        if (cancelled) return;

        let invitedEvents: CalendarEvent[] = [];
        if (participantRows && participantRows.length > 0) {
          const eventIds = participantRows.map((p) => p.event_id);
          const { data: invitedRows } = await supabase
            .from("events")
            .select("*")
            .in("id", eventIds)
            .eq("week_start", weekStart);

          if (cancelled) return;

          if (invitedRows && invitedRows.length > 0) {
            // Fetch owner display names
            const ownerIds = [...new Set(invitedRows.map((r) => r.user_id as string))];
            const { data: profiles } = await supabase
              .from("profiles")
              .select("id, display_name")
              .in("id", ownerIds);

            if (cancelled) return;

            const profileMap = new Map(
              (profiles || []).map((p) => [p.id, p.display_name || ""])
            );

            invitedEvents = invitedRows
              .map((row) => {
                const event = rowToEvent(row);
                event.isInvited = true;
                event.ownerId = row.user_id as string;
                event.ownerName = profileMap.get(row.user_id as string) || "";
                return event;
              })
              .filter(isValidEvent);
          }
        }

        if (!cancelled) {
          setWeek({ weekStart, events: [...ownEvents, ...invitedEvents] });
        }
      } catch {
        if (!cancelled) setError("Failed to load events. Check your connection.");
      }
      if (!cancelled) setLoading(false);
    }

    load();
    return () => { cancelled = true; };
  }, [user, weekStart]);

  const addEvent = useCallback(async (data: NewEventData) => {
    if (!user) return;
    validateEventData(data);

    const supabase = createClient();
    const { data: row, error } = await supabase
      .from("events")
      .insert({
        user_id: user.id,
        week_start: weekStart,
        title: data.title.trim(),
        day_key: data.dayKey,
        start_time: data.startTime || null,
        end_time: data.endTime || null,
        category: data.category,
        note: data.note?.trim() || null,
        status: "planned",
        visibility: data.visibility || "private",
      })
      .select()
      .single();

    if (!error && row) {
      const event = rowToEvent(row);
      setWeek((prev) => ({
        ...prev,
        events: [...prev.events, event],
      }));
    }
  }, [user, weekStart]);

  const updateEvent = useCallback(async (id: string, updates: Partial<Omit<CalendarEvent, "id" | "createdAt">>) => {
    if (!user) return;
    validateEventData(updates);

    // Map frontend field names to DB column names
    const dbUpdates: Record<string, unknown> = {};
    if (updates.title !== undefined) dbUpdates.title = updates.title;
    if (updates.dayKey !== undefined) dbUpdates.day_key = updates.dayKey;
    if (updates.startTime !== undefined) dbUpdates.start_time = updates.startTime || null;
    if (updates.endTime !== undefined) dbUpdates.end_time = updates.endTime || null;
    if (updates.category !== undefined) dbUpdates.category = updates.category;
    if (updates.status !== undefined) dbUpdates.status = updates.status;
    if (updates.note !== undefined) dbUpdates.note = updates.note || null;
    if (updates.visibility !== undefined) dbUpdates.visibility = updates.visibility;

    const supabase = createClient();
    const { error } = await supabase
      .from("events")
      .update(dbUpdates)
      .eq("id", id)
      .eq("user_id", user.id);

    if (!error) {
      setWeek((prev) => ({
        ...prev,
        events: prev.events.map((e) => (e.id === id ? { ...e, ...updates } : e)),
      }));
    }
  }, [user]);

  const deleteEvent = useCallback(async (id: string) => {
    if (!user) return;

    const supabase = createClient();
    const { error } = await supabase
      .from("events")
      .delete()
      .eq("id", id)
      .eq("user_id", user.id);

    if (!error) {
      setWeek((prev) => ({
        ...prev,
        events: prev.events.filter((e) => e.id !== id),
      }));
    }
  }, [user]);

  return { week, loading, error, addEvent, updateEvent, deleteEvent };
}
